application: dandubois-net
version: v2-0-0
runtime: go
api_version: go1

handlers:
- url: /_ah/.*
  script: _go_app
  login: admin
- url: /api/.*
  script: _go_app
- url: /dist
  static_dir: web/dist
# Production assets.
- url: /.*
  static_files: web/dist/index.html
  upload: web/dist/index.html
# Development assets. Uncomment to use with `gulp serve`.
# - url: /.*
#   static_files: web/src/index.html
#   upload: web/src/index.html
